---
- hosts: all
  become: yes
  tasks:
  - name: first template task
    template:
      src: firstjinja.j2
      dest: /home/ansible/first
  - name: second template task
    template:
      src: secondjinja.j2
      dest: /home/ansible/second
  - name: tomcat7 default settings
    template:
      src: tomcat7.j2
      dest: /etc/default/tomcat7